/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "API": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}

import "sst"
export {}