import type { AppLocale } from "@/i18n/routing"

const en = [
  "Best treatment for acute pancreatitis based on severity",
  "Best treatment for acute exacerbation of COPD",
  "Best treatment for acute bacterial sinusitis",
  "Best treatment for acute otitis media",
  "Best treatment for community-acquired pneumonia",
  "Best treatment for hypertensive emergency",
  "Best treatment for acute heart failure",
  "Best treatment for gout flare",
  "Management of acute pancreatitis based on severity",
  "Management of acute exacerbation of COPD",
  "Management of diabetic ketoacidosis in adults",
  "Management of hyperkalemia in the emergency setting",
  "Management of sepsis and septic shock",
  "Management of atrial fibrillation with rapid ventricular response",
  "Management of acute coronary syndrome",
  "Management of anaphylaxis in adults",
  "First-line treatment options for acute bacterial sinusitis",
  "First-line treatment for uncomplicated cystitis",
  "First-line treatment for hypertension in diabetes",
  "First-line treatment for osteoarthritis of the knee",
  "First-line treatment for major depressive disorder",
  "First-line treatment for type 2 diabetes",
  "Differential diagnosis of acute chest pain",
  "Differential diagnosis of acute abdominal pain",
  "Differential diagnosis of syncope",
  "Differential diagnosis of fever in a returning traveler",
  "Workup of iron-deficiency anemia",
  "Workup of incidental adrenal nodule",
  "Workup of hyponatremia",
  "Workup of elevated liver enzymes",
  "Dosing of vancomycin in adults with renal impairment",
  "Dosing of enoxaparin for VTE treatment",
  "Dosing of insulin in diabetic ketoacidosis",
  "Contraindications to thrombolysis in acute ischemic stroke",
  "Contraindications to metformin",
  "Contraindications to NSAIDs in heart failure",
  "Diagnostic criteria for acute pancreatitis",
  "When to start antibiotics for acute otitis media",
  "Steroid dosing for acute asthma exacerbation",
  "Fluid resuscitation in septic shock",
]

const zhCn = [
  "最佳治疗：按严重程度处理急性胰腺炎",
  "最佳治疗：急性COPD加重",
  "最佳治疗：急性细菌性鼻窦炎",
  "最佳治疗：急性中耳炎",
  "最佳治疗：社区获得性肺炎",
  "最佳治疗：高血压急症",
  "最佳治疗：急性心力衰竭",
  "最佳治疗：痛风发作",
  "处理要点：按严重程度处理急性胰腺炎",
  "处理要点：急性COPD加重",
  "处理要点：成人糖尿病酮症酸中毒",
  "处理要点：急诊高钾血症",
  "处理要点：脓毒症与感染性休克",
  "处理要点：房颤伴快速心室率",
  "处理要点：急性冠脉综合征",
  "处理要点：成人过敏性休克",
  "一线治疗：急性细菌性鼻窦炎",
  "一线治疗：单纯性膀胱炎",
  "一线治疗：糖尿病合并高血压",
  "一线治疗：膝关节骨关节炎",
  "一线治疗：重性抑郁障碍",
  "一线治疗：2型糖尿病",
  "鉴别诊断：急性胸痛",
  "鉴别诊断：急性腹痛",
  "鉴别诊断：晕厥",
  "鉴别诊断：归国发热",
  "检查评估：缺铁性贫血",
  "检查评估：偶发肾上腺结节",
  "检查评估：低钠血症",
  "检查评估：肝酶升高",
  "剂量：成人肾损害时的万古霉素",
  "剂量：依诺肝素用于静脉血栓治疗",
  "剂量：糖尿病酮症酸中毒的胰岛素",
  "禁忌证：急性缺血性卒中溶栓",
  "禁忌证：二甲双胍",
  "禁忌证：心力衰竭患者使用NSAIDs",
  "急性胰腺炎的诊断标准",
  "急性中耳炎何时开始用抗生素",
  "急性哮喘加重的激素剂量",
  "感染性休克的液体复苏",
]

const zhHk = [
  "最佳治療：按嚴重程度處理急性胰臟炎",
  "最佳治療：急性COPD加重",
  "最佳治療：急性細菌性鼻竇炎",
  "最佳治療：急性中耳炎",
  "最佳治療：社區獲得性肺炎",
  "最佳治療：高血壓急症",
  "最佳治療：急性心臟衰竭",
  "最佳治療：痛風發作",
  "處理要點：按嚴重程度處理急性胰臟炎",
  "處理要點：急性COPD加重",
  "處理要點：成人糖尿病酮症酸中毒",
  "處理要點：急診高鉀血症",
  "處理要點：敗血症與感染性休克",
  "處理要點：房顫伴快速心室率",
  "處理要點：急性冠狀動脈綜合徵",
  "處理要點：成人過敏性休克",
  "一線治療：急性細菌性鼻竇炎",
  "一線治療：單純性膀胱炎",
  "一線治療：糖尿病合併高血壓",
  "一線治療：膝關節骨關節炎",
  "一線治療：重性抑鬱障礙",
  "一線治療：2型糖尿病",
  "鑑別診斷：急性胸痛",
  "鑑別診斷：急性腹痛",
  "鑑別診斷：暈厥",
  "鑑別診斷：歸國發熱",
  "檢查評估：缺鐵性貧血",
  "檢查評估：偶發腎上腺結節",
  "檢查評估：低鈉血症",
  "檢查評估：肝酶升高",
  "劑量：成人腎損害時的萬古霉素",
  "劑量：依諾肝素用於靜脈血栓治療",
  "劑量：糖尿病酮症酸中毒的胰島素",
  "禁忌證：急性缺血性中風溶栓",
  "禁忌證：二甲雙胍",
  "禁忌證：心臟衰竭患者使用NSAIDs",
  "急性胰臟炎的診斷標準",
  "急性中耳炎何時開始用抗生素",
  "急性哮喘加重的激素劑量",
  "感染性休克的液體復甦",
]

export const PROMPT_COMPLETION_PHRASES: Record<AppLocale, readonly string[]> = {
  en,
  "zh-cn": zhCn,
  "zh-hk": zhHk,
}
